---
# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Título
        | Subtítulo
        | Subtítulo
author:
- name: Marcos Antonio González Reyes
  affiliation: Estudiante, Universidad Autónoma de Santo Domingo (UASD)
abstract: "Resumen del manuscrito"
keywords: "Arecaceae, BCI"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib
# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
---

# Introducción


Barro Colorado es una isla localizada en el lago Gatún del Canal de Panamá. Es un área protegida, en la cual se esstudian los bosques tropicales y que junto con otras cinco penínsulas cercanas, forma el Monumento Natural Barro Colorado. Estructurado en 1923 y está administrado por el Instituto Smithsoniano desde 1946.

Forma parte de The Center for Tropical Science, una red compuesta por alrededor de 15 países, que estudian los bosques tropicales y la metología estandarizada en grandes parcelas permanentes, siendo Barro Colorado la primer gran parcela en ser establecida, censada por primera vez en los años 1981-1983 [@condit1998tropical]. Esto con el fin de recolectar y analizar datos ecológicos a fin de monitorear la dinámica de poblaciones y la diversidad en localidades permanentes a largo plazo.

Esto se conoce como Long-Term Monitoring, puede ser definido como el levantamiento de datos durante determinado período de tiempo en áreas contaminadas o con un alto índice de pérdida de especies. En palabras de @lindenmayer2010science, son las mediciones empíricas repetidas basadas en el campo se recopilan continuamente y luego se analizan durante al menos 10 años.

Es un estudio a largo plazo cuando documenta los procesos importantes que componen el ecosistema o el tiempo de generación del organismo dominante, así, su duración se mide con la velocidad dinámica del sistema que se está estudiando [@franklin1989importance].



# Metodología

\ldots

# Resultados

\ldots

# Discusión

# Agradecimientos

# Información de soporte

\ldots

# *Script* reproducible

\ldots

# Referencias
